feat(label): add 'label option for new flightresult component' option
AlaskaAirlines/auro-badge pull request #4
Opened 2021-01-27 23:51 UTC by aesthetiques

# Alaska Airlines Pull Request

Adds the label option for auro-badge
![image](https://user-images.githubusercontent.com/25255197/106069309-23c00300-60b7-11eb-97ed-239b64f6f276.png)

This will be used in conjunction with other components to build a single result on the flight results page. No change to other functionality.

## Type of change:

Please delete options that are not relevant.

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-01-27 23:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-badge?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-badge?pullRequest=4) before we can accept your contribution.<br/><hr/>**Caleb Wells** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-badge?pullRequest=4) it.</sub>

2021-01-28 18:15 UTC, gusnaughton commented
@erikalanghauser please leave your review here for http://wakeful-grape.surge.sh/

2021-01-28 18:50 UTC, blackfalcon approved these changes

2021-01-28 18:52 UTC, blackfalcon commented on src/style.scss
> +  padding: 4px 6px;
Why is this moved to hard pixels? The badge supports the `fixed` feature. 

Please move back to the REM values.

2021-01-28 18:53 UTC, blackfalcon requested changes
Please see comments about pixel values.

2021-01-28 21:09 UTC, blackfalcon approved these changes

2021-01-28 21:10 UTC, merged

2021-01-28 21:13 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-badge/v/1.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-badge/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: